//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RentalInRome.WsChnlHoliday_Enquiries {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="enquiriesSoap", Namespace="http://holidaylettings.co.uk/webservices/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    public partial class enquiries : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private OAuthSoapHeader oAuthSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback FetchEnquiriesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public enquiries() {
            this.Url = global::RentalInRome.Properties.Settings.Default.RentalInRome_WsChnlHoliday_Enquiries_enquiries;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public OAuthSoapHeader OAuthSoapHeaderValue {
            get {
                return this.oAuthSoapHeaderValueField;
            }
            set {
                this.oAuthSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FetchEnquiriesCompletedEventHandler FetchEnquiriesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OAuthSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://holidaylettings.co.uk/webservices/FetchEnquiries", RequestNamespace="http://holidaylettings.co.uk/webservices/", ResponseNamespace="http://holidaylettings.co.uk/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FetchWebServiceResponseOfEnquiryDto FetchEnquiries(long ownerId, string key, FetchEnquiriesRequest request) {
            object[] results = this.Invoke("FetchEnquiries", new object[] {
                        ownerId,
                        key,
                        request});
            return ((FetchWebServiceResponseOfEnquiryDto)(results[0]));
        }
        
        /// <remarks/>
        public void FetchEnquiriesAsync(long ownerId, string key, FetchEnquiriesRequest request) {
            this.FetchEnquiriesAsync(ownerId, key, request, null);
        }
        
        /// <remarks/>
        public void FetchEnquiriesAsync(long ownerId, string key, FetchEnquiriesRequest request, object userState) {
            if ((this.FetchEnquiriesOperationCompleted == null)) {
                this.FetchEnquiriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchEnquiriesOperationCompleted);
            }
            this.InvokeAsync("FetchEnquiries", new object[] {
                        ownerId,
                        key,
                        request}, this.FetchEnquiriesOperationCompleted, userState);
        }
        
        private void OnFetchEnquiriesOperationCompleted(object arg) {
            if ((this.FetchEnquiriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchEnquiriesCompleted(this, new FetchEnquiriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://holidaylettings.co.uk/webservices/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://holidaylettings.co.uk/webservices/", IsNullable=false)]
    public partial class OAuthSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string oauthTokenField;
        
        private string oauthTokenSecretField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string OauthToken {
            get {
                return this.oauthTokenField;
            }
            set {
                this.oauthTokenField = value;
            }
        }
        
        /// <remarks/>
        public string OauthTokenSecret {
            get {
                return this.oauthTokenSecretField;
            }
            set {
                this.oauthTokenSecretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://holidaylettings.co.uk/webservices/")]
    public partial class WebServiceResponse {
        
        private bool successField;
        
        private int errorCodeField;
        
        private string[] messagesField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://holidaylettings.co.uk/webservices/")]
    public partial class Enquiry {
        
        private long enquiryIdField;
        
        private long homeIdField;
        
        private string fromEmailField;
        
        private string toEmailField;
        
        private System.Nullable<System.DateTime> holidayStartDateField;
        
        private System.Nullable<System.DateTime> holidayEndDateField;
        
        private System.Nullable<int> guestsAdultsField;
        
        private System.Nullable<int> guestsChildrenField;
        
        private System.DateTime enquiryDateField;
        
        private string sourceField;
        
        private string fromNameField;
        
        private string fromTelephoneField;
        
        private string messageField;
        
        /// <remarks/>
        public long EnquiryId {
            get {
                return this.enquiryIdField;
            }
            set {
                this.enquiryIdField = value;
            }
        }
        
        /// <remarks/>
        public long HomeId {
            get {
                return this.homeIdField;
            }
            set {
                this.homeIdField = value;
            }
        }
        
        /// <remarks/>
        public string FromEmail {
            get {
                return this.fromEmailField;
            }
            set {
                this.fromEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ToEmail {
            get {
                return this.toEmailField;
            }
            set {
                this.toEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> HolidayStartDate {
            get {
                return this.holidayStartDateField;
            }
            set {
                this.holidayStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> HolidayEndDate {
            get {
                return this.holidayEndDateField;
            }
            set {
                this.holidayEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GuestsAdults {
            get {
                return this.guestsAdultsField;
            }
            set {
                this.guestsAdultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GuestsChildren {
            get {
                return this.guestsChildrenField;
            }
            set {
                this.guestsChildrenField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EnquiryDate {
            get {
                return this.enquiryDateField;
            }
            set {
                this.enquiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string FromName {
            get {
                return this.fromNameField;
            }
            set {
                this.fromNameField = value;
            }
        }
        
        /// <remarks/>
        public string FromTelephone {
            get {
                return this.fromTelephoneField;
            }
            set {
                this.fromTelephoneField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://holidaylettings.co.uk/webservices/")]
    public partial class FetchWebServiceResponseOfEnquiryDto {
        
        private Enquiry[] fetchedDataField;
        
        private WebServiceResponse webServiceResponseField;
        
        /// <remarks/>
        public Enquiry[] FetchedData {
            get {
                return this.fetchedDataField;
            }
            set {
                this.fetchedDataField = value;
            }
        }
        
        /// <remarks/>
        public WebServiceResponse WebServiceResponse {
            get {
                return this.webServiceResponseField;
            }
            set {
                this.webServiceResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FetchEnquiriesRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://holidaylettings.co.uk/webservices/")]
    public abstract partial class Request {
        
        private System.Nullable<bool> testField;
        
        private System.Nullable<long> recordsAffectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> RecordsAffected {
            get {
                return this.recordsAffectedField;
            }
            set {
                this.recordsAffectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://holidaylettings.co.uk/webservices/")]
    public partial class FetchEnquiriesRequest : Request {
        
        private System.Nullable<long> homeIdField;
        
        private System.Nullable<System.DateTime> fromDateField;
        
        private System.Nullable<long> fetchedEnquiriesLimitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> HomeId {
            get {
                return this.homeIdField;
            }
            set {
                this.homeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> FetchedEnquiriesLimit {
            get {
                return this.fetchedEnquiriesLimitField;
            }
            set {
                this.fetchedEnquiriesLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void FetchEnquiriesCompletedEventHandler(object sender, FetchEnquiriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchEnquiriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchEnquiriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchWebServiceResponseOfEnquiryDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchWebServiceResponseOfEnquiryDto)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591