//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RentalInRome.WS_Eco {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSSoap", Namespace="http://ecopulizie.it/")]
    public partial class WS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback Authentication_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback LocationEvent_Insert_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback LocationEvent_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LocationEvent_DeleteListOperationCompleted;
        
        private System.Threading.SendOrPostCallback Location_Insert_UpdateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS() {
            this.Url = global::RentalInRome.Properties.Settings.Default.RentalInRome_WS_eco_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event Authentication_TestCompletedEventHandler Authentication_TestCompleted;
        
        /// <remarks/>
        public event LocationEvent_Insert_UpdateCompletedEventHandler LocationEvent_Insert_UpdateCompleted;
        
        /// <remarks/>
        public event LocationEvent_DeleteCompletedEventHandler LocationEvent_DeleteCompleted;
        
        /// <remarks/>
        public event LocationEvent_DeleteListCompletedEventHandler LocationEvent_DeleteListCompleted;
        
        /// <remarks/>
        public event Location_Insert_UpdateCompletedEventHandler Location_Insert_UpdateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ecopulizie.it/HelloWorld", RequestNamespace="http://ecopulizie.it/", ResponseNamespace="http://ecopulizie.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ecopulizie.it/Authentication_Test", RequestNamespace="http://ecopulizie.it/", ResponseNamespace="http://ecopulizie.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Authentication_Test() {
            object[] results = this.Invoke("Authentication_Test", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Authentication_TestAsync() {
            this.Authentication_TestAsync(null);
        }
        
        /// <remarks/>
        public void Authentication_TestAsync(object userState) {
            if ((this.Authentication_TestOperationCompleted == null)) {
                this.Authentication_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthentication_TestOperationCompleted);
            }
            this.InvokeAsync("Authentication_Test", new object[0], this.Authentication_TestOperationCompleted, userState);
        }
        
        private void OnAuthentication_TestOperationCompleted(object arg) {
            if ((this.Authentication_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Authentication_TestCompleted(this, new Authentication_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ecopulizie.it/LocationEvent_Insert_Update", RequestNamespace="http://ecopulizie.it/", ResponseNamespace="http://ecopulizie.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LocationEvent_Insert_Update(int ref_id_caller, int ref_pid_event, int ref_pid_location, int is_to_verify, System.DateTime dtRentStart, System.DateTime dtRentEnd, string rent_client_name, int person_qty, string ref_eventNotes, out string errorMsg) {
            object[] results = this.Invoke("LocationEvent_Insert_Update", new object[] {
                        ref_id_caller,
                        ref_pid_event,
                        ref_pid_location,
                        is_to_verify,
                        dtRentStart,
                        dtRentEnd,
                        rent_client_name,
                        person_qty,
                        ref_eventNotes});
            errorMsg = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LocationEvent_Insert_UpdateAsync(int ref_id_caller, int ref_pid_event, int ref_pid_location, int is_to_verify, System.DateTime dtRentStart, System.DateTime dtRentEnd, string rent_client_name, int person_qty, string ref_eventNotes) {
            this.LocationEvent_Insert_UpdateAsync(ref_id_caller, ref_pid_event, ref_pid_location, is_to_verify, dtRentStart, dtRentEnd, rent_client_name, person_qty, ref_eventNotes, null);
        }
        
        /// <remarks/>
        public void LocationEvent_Insert_UpdateAsync(int ref_id_caller, int ref_pid_event, int ref_pid_location, int is_to_verify, System.DateTime dtRentStart, System.DateTime dtRentEnd, string rent_client_name, int person_qty, string ref_eventNotes, object userState) {
            if ((this.LocationEvent_Insert_UpdateOperationCompleted == null)) {
                this.LocationEvent_Insert_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocationEvent_Insert_UpdateOperationCompleted);
            }
            this.InvokeAsync("LocationEvent_Insert_Update", new object[] {
                        ref_id_caller,
                        ref_pid_event,
                        ref_pid_location,
                        is_to_verify,
                        dtRentStart,
                        dtRentEnd,
                        rent_client_name,
                        person_qty,
                        ref_eventNotes}, this.LocationEvent_Insert_UpdateOperationCompleted, userState);
        }
        
        private void OnLocationEvent_Insert_UpdateOperationCompleted(object arg) {
            if ((this.LocationEvent_Insert_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LocationEvent_Insert_UpdateCompleted(this, new LocationEvent_Insert_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ecopulizie.it/LocationEvent_Delete", RequestNamespace="http://ecopulizie.it/", ResponseNamespace="http://ecopulizie.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LocationEvent_Delete(int ref_id_caller, int ref_pid_event, out string errorMsg) {
            object[] results = this.Invoke("LocationEvent_Delete", new object[] {
                        ref_id_caller,
                        ref_pid_event});
            errorMsg = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LocationEvent_DeleteAsync(int ref_id_caller, int ref_pid_event) {
            this.LocationEvent_DeleteAsync(ref_id_caller, ref_pid_event, null);
        }
        
        /// <remarks/>
        public void LocationEvent_DeleteAsync(int ref_id_caller, int ref_pid_event, object userState) {
            if ((this.LocationEvent_DeleteOperationCompleted == null)) {
                this.LocationEvent_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocationEvent_DeleteOperationCompleted);
            }
            this.InvokeAsync("LocationEvent_Delete", new object[] {
                        ref_id_caller,
                        ref_pid_event}, this.LocationEvent_DeleteOperationCompleted, userState);
        }
        
        private void OnLocationEvent_DeleteOperationCompleted(object arg) {
            if ((this.LocationEvent_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LocationEvent_DeleteCompleted(this, new LocationEvent_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ecopulizie.it/LocationEvent_DeleteList", RequestNamespace="http://ecopulizie.it/", ResponseNamespace="http://ecopulizie.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LocationEvent_DeleteList(int ref_id_caller, [System.Xml.Serialization.XmlArrayItemAttribute()] System.Nullable<int>[] ref_pid_event_list, out string errorMsg) {
            object[] results = this.Invoke("LocationEvent_DeleteList", new object[] {
                        ref_id_caller,
                        ref_pid_event_list});
            errorMsg = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LocationEvent_DeleteListAsync(int ref_id_caller, System.Nullable<int>[] ref_pid_event_list) {
            this.LocationEvent_DeleteListAsync(ref_id_caller, ref_pid_event_list, null);
        }
        
        /// <remarks/>
        public void LocationEvent_DeleteListAsync(int ref_id_caller, System.Nullable<int>[] ref_pid_event_list, object userState) {
            if ((this.LocationEvent_DeleteListOperationCompleted == null)) {
                this.LocationEvent_DeleteListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocationEvent_DeleteListOperationCompleted);
            }
            this.InvokeAsync("LocationEvent_DeleteList", new object[] {
                        ref_id_caller,
                        ref_pid_event_list}, this.LocationEvent_DeleteListOperationCompleted, userState);
        }
        
        private void OnLocationEvent_DeleteListOperationCompleted(object arg) {
            if ((this.LocationEvent_DeleteListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LocationEvent_DeleteListCompleted(this, new LocationEvent_DeleteListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ecopulizie.it/Location_Insert_Update", RequestNamespace="http://ecopulizie.it/", ResponseNamespace="http://ecopulizie.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Location_Insert_Update(string code, int ref_id, int ref_pid_location, int is_active, int single_bed_quantity, int double_bed_quantity, int bathroom_quantity, int num_persons_min, int num_persons_max, decimal mqTotal, string latitude_longitude, OwnerParams ownerParams, out string errorMsg) {
            object[] results = this.Invoke("Location_Insert_Update", new object[] {
                        code,
                        ref_id,
                        ref_pid_location,
                        is_active,
                        single_bed_quantity,
                        double_bed_quantity,
                        bathroom_quantity,
                        num_persons_min,
                        num_persons_max,
                        mqTotal,
                        latitude_longitude,
                        ownerParams});
            errorMsg = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Location_Insert_UpdateAsync(string code, int ref_id, int ref_pid_location, int is_active, int single_bed_quantity, int double_bed_quantity, int bathroom_quantity, int num_persons_min, int num_persons_max, decimal mqTotal, string latitude_longitude, OwnerParams ownerParams) {
            this.Location_Insert_UpdateAsync(code, ref_id, ref_pid_location, is_active, single_bed_quantity, double_bed_quantity, bathroom_quantity, num_persons_min, num_persons_max, mqTotal, latitude_longitude, ownerParams, null);
        }
        
        /// <remarks/>
        public void Location_Insert_UpdateAsync(string code, int ref_id, int ref_pid_location, int is_active, int single_bed_quantity, int double_bed_quantity, int bathroom_quantity, int num_persons_min, int num_persons_max, decimal mqTotal, string latitude_longitude, OwnerParams ownerParams, object userState) {
            if ((this.Location_Insert_UpdateOperationCompleted == null)) {
                this.Location_Insert_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocation_Insert_UpdateOperationCompleted);
            }
            this.InvokeAsync("Location_Insert_Update", new object[] {
                        code,
                        ref_id,
                        ref_pid_location,
                        is_active,
                        single_bed_quantity,
                        double_bed_quantity,
                        bathroom_quantity,
                        num_persons_min,
                        num_persons_max,
                        mqTotal,
                        latitude_longitude,
                        ownerParams}, this.Location_Insert_UpdateOperationCompleted, userState);
        }
        
        private void OnLocation_Insert_UpdateOperationCompleted(object arg) {
            if ((this.Location_Insert_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Location_Insert_UpdateCompleted(this, new Location_Insert_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ecopulizie.it/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ecopulizie.it/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ecopulizie.it/")]
    public partial class OwnerParams {
        
        private int idField;
        
        private string nameFullField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string nameFull {
            get {
                return this.nameFullField;
            }
            set {
                this.nameFullField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Authentication_TestCompletedEventHandler(object sender, Authentication_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Authentication_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Authentication_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void LocationEvent_Insert_UpdateCompletedEventHandler(object sender, LocationEvent_Insert_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LocationEvent_Insert_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LocationEvent_Insert_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void LocationEvent_DeleteCompletedEventHandler(object sender, LocationEvent_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LocationEvent_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LocationEvent_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void LocationEvent_DeleteListCompletedEventHandler(object sender, LocationEvent_DeleteListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LocationEvent_DeleteListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LocationEvent_DeleteListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Location_Insert_UpdateCompletedEventHandler(object sender, Location_Insert_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Location_Insert_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Location_Insert_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591