//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalInRome.admin {
    
    
    public partial class rnt_estate_interns {
        
        /// <summary>
        /// UC_rnt_estate_navlinks1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RentalInRome.admin.uc.UC_rnt_estate_navlinks UC_rnt_estate_navlinks1;
        
        /// <summary>
        /// UC_InternMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MagaRentalCE.admin.modRental.ucEstateDett.EstateInternsMain UC_InternMain;
    }
}
